version: 2

requirements:
  signed_off_by:
    required: true

# Disallow approval of PRs still under development
always_pending:
  title_regex: 'WIP'
  labels:
    - do-not-merge
    - on-hold
    - wip
  explanation: 'Work in progress - do not merge'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(LGTM|lgtm|Approved|\+1|:\+1:)'
    reject_regex: '^(Rejected|-1|:-1:)'
  reset_on_push:
    enabled: false
  reset_on_reopened:
    enabled: false
  author_approval:
    ignored: true

groups:
  code-reviewers:
    required: 2
    teams:
      - clear-containers-intel
  qa:
    required: 0
    users:
      - chavafg
      - gabyct
    approve_by_comment:
      enabled: true
      approve_regex: '^qa-passed'
      reject_regex: '^qa-failed'

  docs-team:
    conditions:
      files:
        - "documentation/*"
        - "*.md"
        - "*.rst"
    required: 1
    users:
      - rcaballeromx
      - mltullis
    approve_by_comment:
      enabled: true
      approve_regex: '^docs-passed'
      reject_regex: '^docs-failed'
