sudo: required
dist: trusty

language: c
compiler:
- gcc
- clang

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
  - secure: d0zhKrx7WLvmanHarNQmGcDMfj1Z24Z8oQkXno+5vJBXXEbnjzoYwAY+bppEA3vCOuLUEwpy+VDcbSOd6tAB00mYzFi24Eq9gHSsvaafKQOkD+OzxGy/J0vINcKR7YEPIYw4rzxwQlbOuS/o7WcJPHydBSW8vQDnUdnXdxBUwUECnzeyFQZ7bsmiStV+3wye8QfYHPGOXXpQfmnxzNtYsjkaTooiDEW2v7cdhd6Ws4nzqCE6rrtOvsC/DrXvj1daNfsg1f7WNYAWxjTfybQUaTtoBCVu8spQ0rmpxIGrhsUxpLpiiJeSdL73IVHtjuHIuxjvxLL3O9m9WN5dSzAzKNqe2jdk3+CPvxwbGIcZMdoGXSTgpyOyaj9oKjMEY+P4YOOF8egDZZMTh60jev5uZXq0dRceLRLyF/7JvYRqkfWLlpI2tOFj4TqMltvl8yXFqmZbOqoSwSjQ7ss4/Bip+4hP1e9uwBhgxKGtfUuo0xa6uSlJ9yfrnxkIldc3ULXqlMv+EcAdYADPaPbVGf5MmvVhHle34uWy6JDNY3Bu6dCy6cc+h9/40i/wLT/nZMw+wdL6/h9PyJBqtQLqqF/GzSAXw7zMj9KLbaETzDKCZiLb7AmHKagnJfM7M4zTPzeK57TA31o5B8H6RTu0HO7rRWgGaQshNVONmQJRq0m9PAc=
  # Only run for the default compiler to minimise the impact on the
  # projects Coverity Scan quota.
  - coverity_scan_run_condition='"$CC" = gcc'

before_script:
- "./.ci/ci-pre-checks.sh"
- "./.ci/ci-setup.sh"

script:
- "./.ci/ci-build.sh"

after_failure:
- "./.ci/ci-teardown.sh"

notifications:
  email:
    recipients:
    - cc-devel@lists.01.org
    on_success: change
    on_failure: always
  slack:
    secure: l/E9H4p6KHHBU+BHetJoQ1OoyNeVKmcW5NHhmBxTq10n2orM0fbLjYQUWMnsvdxL11uzS/QtoA3uan5rVlqKllazk59iqO7iGkNrecdyvyeTHwT7PWsXy36VgYahX5MXusRi+zPCS1rnKszPKOXdRIqqMIOv+T8zvkKK2RdZFZtsc0k/uKzxMunUm5nBaG7WUmm5ZyEULJ4rZiZ3i1t/BwpMnBlbOt+CO18xhfKz1lcMBWa74wajpsjNtMPNptYrkaw2mmBiIWtkUWE7Gap6Y+93ynxX+B+OfvwRLwKDoWil3j6bG7zIpXEMZnLURoiH+VaVvc8/tmQF2F6jq5+jobm+SrqWIQw1JebdPdhVMytYQj5YmgDcXAXMnk2opxSVKli+EuQn4TilYLfTPkRYZJ4fJIjj5NwhE31CyfHOrTI1jjdAzROo9hdR3L3uyQfLYwo00r4GINYfQOLfkERSaax+r9uZGGzMZYQ9tnz+xQw84mH7MUp01s+tom9/AuDhypusDy7OMmJwq1cyBzSxdWbZnfIsfnj57a/4XAdIr7g/XSK5pmPdkDj3aZ3XRwuP9SlVkEqiXi5x1M0vxapQPjwd/el4uwTUq9UW8s+GPjuNZSzqopD2XIP8Avgm2+zO146SH2MZLiJdLiBv3XV0IXmCuKXZeEUU9uINB7GiHFk=

addons:
  coverity_scan:
    project:
      name: 01org/cc-oci-runtime
      description: Build submitted via Travis CI
    build_command_prepend: "./.ci/ci-configure.sh; make clean"
    build_command: make -j5
    branch_pattern: coverity_scan
    # It should be possible to specify the Coverity notification email
    # using environment variable COVERITY_SCAN_NOTIFICATION_EMAIL
    # (standard, encrypted, or repository type).
    #
    # However, the Travis logs show this variable is silently unset
    # before Travis passes the information to the Coverity addon.
    notification_email: james.o.hunt@intel.com
