sudo: required
dist: trusty
branches:
  only:
    - master

language: c
compiler: gcc

before_script:
- ./.travis-setup.sh

script:
- ./autogen.sh --enable-cppcheck --enable-valgrind
- make

notifications:
  email:
    recipients:
      - cc-devel@lists.01.org
    on_success: change
    on_failure: always
