sudo: required
dist: trusty

language: c
compiler:
  - gcc
  - clang

env:
  global:
    - PATH=/usr/local/bin:$PATH
    - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
    - ACLOCAL_FLAGS="-I /usr/local/share/aclocal $ACLOCAL_FLAG"

before_script:
- ./.travis-setup.sh

script:
- ./autogen.sh --enable-cppcheck --enable-valgrind --disable-silent-rules
- make

notifications:
  email:
    recipients:
      - cc-devel@lists.01.org
    on_success: change
    on_failure: always
